In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv('data/cases_2010.csv',engine='python',on_bad_lines='skip')

In [3]:
df.shape

(4281327, 19)

In [4]:
df.columns

Index(['ddl_case_id', 'year', 'state_code', 'dist_code', 'court_no', 'cino',
       'judge_position', 'female_defendant', 'female_petitioner',
       'female_adv_def', 'female_adv_pet', 'type_name', 'purpose_name',
       'disp_name', 'date_of_filing', 'date_of_decision', 'date_first_list',
       'date_last_list', 'date_next_list'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4281327 entries, 0 to 4281326
Data columns (total 19 columns):
 #   Column             Dtype
---  ------             -----
 0   ddl_case_id        str
 1   year               int64
 2   state_code         int64
 3   dist_code          int64
 4   court_no           int64
 5   cino               str
 6   judge_position     str
 7   female_defendant   str
 8   female_petitioner  str
 9   female_adv_def     int64
 10  female_adv_pet     int64
 11  type_name          int64
 12  purpose_name       float64
 13  disp_name          int64
 14  date_of_filing     str
 15  date_of_decision   str
 16  date_first_list    str
 17  date_last_list     str
 18  date_next_list     str
dtypes: float64(1), int64(8), str(10)
memory usage: 620.6 MB

In [6]:
df1 =pd.read_csv('data/cases_2011.csv',engine='python',on_bad_lines='skip')
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5208653 entries, 0 to 5208652
Data columns (total 19 columns):
 #   Column             Dtype
---  ------             -----
 0   ddl_case_id        str
 1   year               int64
 2   state_code         int64
 3   dist_code          int64
 4   court_no           int64
 5   cino               str
 6   judge_position     str
 7   female_defendant   str
 8   female_petitioner  str
 9   female_adv_def     int64
 10  female_adv_pet     int64
 11  type_name          int64
 12  purpose_name       float64
 13  disp_name          int64
 14  date_of_filing     str
 15  date_of_decision   str
 16  date_first_list    str
 17  date_last_list     str
 18  date_next_list     str
dtypes: float64(1), int64(8), str(10)
memory usage: 755.0 MB

In [7]:
df2 =pd.read_csv('data/cases_2012.csv',engine='python',on_bad_lines='skip')
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 6400783 entries, 0 to 6400782
Data columns (total 19 columns):
 #   Column             Dtype
---  ------             -----
 0   ddl_case_id        str
 1   year               int64
 2   state_code         int64
 3   dist_code          int64
 4   court_no           int64
 5   cino               str
 6   judge_position     str
 7   female_defendant   str
 8   female_petitioner  str
 9   female_adv_def     int64
 10  female_adv_pet     int64
 11  type_name          int64
 12  purpose_name       float64
 13  disp_name          int64
 14  date_of_filing     str
 15  date_of_decision   str
 16  date_first_list    str
 17  date_last_list     str
 18  date_next_list     str
dtypes: float64(1), int64(8), str(10)
memory usage: 927.8 MB

In [8]:
# df3 =pd.read_csv('data/cases_2013.csv',engine='python',on_bad_lines='skip')
# df3.info()

In [9]:
# df4 =pd.read_csv('data/cases_2014.csv',engine='python',on_bad_lines='skip')
# df4.info()

In [10]:
# df5 =pd.read_csv('data/cases_2015.csv',engine='python',on_bad_lines='skip')
# df5.info()

In [11]:
print(df.shape)
print(df1.shape)
print(df2.shape)
# print(df3.shape)
# print(df4.shape)
# print(df5.shape)

(4281327, 19)
(5208653, 19)
(6400783, 19)

In [12]:
data=pd.concat([df,df1,df2],ignore_index=True)

In [13]:
data['year'].value_counts().sort_values()

year
2010    4281327
2011    5208653
2012    6400783
Name: count, dtype: int64

In [14]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 15890763 entries, 0 to 15890762
Data columns (total 19 columns):
 #   Column             Dtype
---  ------             -----
 0   ddl_case_id        str
 1   year               int64
 2   state_code         int64
 3   dist_code          int64
 4   court_no           int64
 5   cino               str
 6   judge_position     str
 7   female_defendant   str
 8   female_petitioner  str
 9   female_adv_def     int64
 10  female_adv_pet     int64
 11  type_name          int64
 12  purpose_name       float64
 13  disp_name          int64
 14  date_of_filing     str
 15  date_of_decision   str
 16  date_first_list    str
 17  date_last_list     str
 18  date_next_list     str
dtypes: float64(1), int64(8), str(10)
memory usage: 2.2 GB

In [15]:
data.shape

(15890763, 19)

In [16]:
data['judge_position'].value_counts()

judge_position
district and sessions court                           2905902
chief judicial magistrate                             2074134
judicial magistrate court                             1524623
civil court                                           1218437
civil judge junior division                            893367
                                                       ...
jjb-jaisalmer district hq                                   1
gramanyalaya, junagarh                                      1
sanjeli_taluka                                              1
special court for trial of cases under the prevent          1
special court for atrocities against women                  1
Name: count, Length: 476, dtype: int64

In [17]:
data.describe()

,year,state_code,dist_code,court_no,female_adv_def,female_adv_pet,type_name,purpose_name,disp_name
count,1.589076e+07,1.589076e+07,1.589076e+07,1.589076e+07,1.589076e+07,1.589076e+07,1.589076e+07,1.510396e+07,1.589076e+07
mean,2.011133e+03,1.051788e+01,1.851851e+01,6.036764e+00,-7.934395e+03,-5.636724e+03,2.959536e+03,3.098937e+03,2.431908e+01
std,8.089698e-01,8.002322e+00,1.436878e+01,6.368923e+00,4.047382e+03,4.958654e+03,1.703935e+03,1.833827e+03,1.279115e+01
min,2.010000e+03,1.000000e+00,1.000000e+00,1.000000e+00,-9.999000e+03,-9.999000e+03,1.000000e+00,1.000000e+00,1.000000e+00
25%,2.010000e+03,3.000000e+00,7.000000e+00,2.000000e+00,-9.999000e+03,-9.999000e+03,1.473000e+03,1.604000e+03,1.900000e+01
50%,2.011000e+03,1.000000e+01,1.600000e+01,3.000000e+00,-9.999000e+03,-9.998000e+03,2.756000e+03,3.258000e+03,2.500000e+01
75%,2.012000e+03,1.600000e+01,2.600000e+01,8.000000e+00,-9.999000e+03,0.000000e+00,4.517000e+03,4.501000e+03,3.000000e+01
max,2.012000e+03,3.300000e+01,7.600000e+01,7.500000e+01,1.000000e+00,1.000000e+00,6.817000e+03,7.331000e+03,5.100000e+01

In [18]:
data.isnull().sum()

ddl_case_id                0
year                       0
state_code                 0
dist_code                  0
court_no                   0
cino                       0
judge_position             0
female_defendant           0
female_petitioner          0
female_adv_def             0
female_adv_pet             0
type_name                  0
purpose_name          786803
disp_name                  0
date_of_filing             0
date_of_decision     2133077
date_first_list       901828
date_last_list        107886
date_next_list        479011
dtype: int64

In [19]:
data['purpose_name'].value_counts()

purpose_name
2688.0    905899
2461.0    765817
1963.0    625694
4501.0    559216
4126.0    512642
           ...
6836.0         1
7034.0         1
6794.0         1
6909.0         1
7170.0         1
Name: count, Length: 7331, dtype: int64

In [20]:
print((data["purpose_name"] == 0).sum())

0

In [21]:
# handling missing values of purpose_name
data['purpose_name']=data['purpose_name'].fillna(0)
data['purpose_name'].isnull().sum()

np.int64(0)

In [22]:
# now we handling the missing values of date_of_decision
data['date_of_decision'].isnull().sum()

np.int64(2133077)

In [23]:
data=data.dropna(subset=['date_of_decision'])

In [24]:
data['date_of_decision'].isnull().sum()

np.int64(0)

In [25]:
data.isnull().sum()

ddl_case_id               0
year                      0
state_code                0
dist_code                 0
court_no                  0
cino                      0
judge_position            0
female_defendant          0
female_petitioner         0
female_adv_def            0
female_adv_pet            0
type_name                 0
purpose_name              0
disp_name                 0
date_of_filing            0
date_of_decision          0
date_first_list      854502
date_last_list       107502
date_next_list       452109
dtype: int64

In [26]:
# now handling the missing values of date_first_list,date_last_list,date_next_list we will actually drop those columns
data=data.drop(columns=['date_first_list'])
data=data.drop(columns=['date_last_list'])
data=data.drop(columns=['date_next_list'])

In [27]:
data.isnull().sum()

ddl_case_id          0
year                 0
state_code           0
dist_code            0
court_no             0
cino                 0
judge_position       0
female_defendant     0
female_petitioner    0
female_adv_def       0
female_adv_pet       0
type_name            0
purpose_name         0
disp_name            0
date_of_filing       0
date_of_decision     0
dtype: int64

In [28]:
data.shape

(13757686, 16)

In [29]:
# now we creating the delay_days columns for target variable
# but first we have to create datetime columns

data['date_of_decision']=pd.to_datetime(data['date_of_decision'],errors='coerce')
data['date_of_filing']=pd.to_datetime(data['date_of_filing'],errors='coerce')

data['delays_days']=(data['date_of_decision']-data['date_of_filing']).dt.days

In [30]:
data.columns

Index(['ddl_case_id', 'year', 'state_code', 'dist_code', 'court_no', 'cino',
       'judge_position', 'female_defendant', 'female_petitioner',
       'female_adv_def', 'female_adv_pet', 'type_name', 'purpose_name',
       'disp_name', 'date_of_filing', 'date_of_decision', 'delays_days'],
      dtype='str')

In [31]:
data.info()

<class 'pandas.DataFrame'>
Index: 13757686 entries, 0 to 15890762
Data columns (total 17 columns):
 #   Column             Dtype
---  ------             -----
 0   ddl_case_id        str
 1   year               int64
 2   state_code         int64
 3   dist_code          int64
 4   court_no           int64
 5   cino               str
 6   judge_position     str
 7   female_defendant   str
 8   female_petitioner  str
 9   female_adv_def     int64
 10  female_adv_pet     int64
 11  type_name          int64
 12  purpose_name       float64
 13  disp_name          int64
 14  date_of_filing     datetime64[us]
 15  date_of_decision   datetime64[us]
 16  delays_days        int64
dtypes: datetime64[us](2), float64(1), int64(9), str(5)
memory usage: 1.8 GB

In [32]:
data["delays_days"].isnull().sum()

np.int64(0)

In [33]:
missing_delay = data[data["delays_days"].isna()]

print(missing_delay[
    ["date_of_filing", "date_of_decision", "delays_days"]
])

Empty DataFrame
Columns: [date_of_filing, date_of_decision, delays_days]
Index: []

In [34]:
print("Missing filing dates:",
      data["date_of_filing"].isna().sum())

print("Missing decision dates:",
      data["date_of_decision"].isna().sum())

Missing filing dates: 0
Missing decision dates: 0

In [35]:
print("Negative delays:",
      (data["delays_days"] < 0).sum())

Negative delays: 68204

In [36]:
data = data.dropna(subset=["delays_days"]).copy()

In [37]:
print(data["delays_days"].isna().sum())

0

In [38]:
negative = data[data["delays_days"] < 0]

print(
    negative[
        ["year", "date_of_filing", "date_of_decision", "delays_days"]
    ].head(20)
)

       year date_of_filing date_of_decision  delays_days
3166   2010     2010-01-07       2010-01-04           -3
4487   2010     2010-12-22       2010-12-02          -20
5453   2010     2010-10-30       2010-03-06         -238
10353  2010     2010-11-08       2010-11-01           -7
12115  2010     2010-03-30       2010-03-29           -1
12238  2010     2010-04-13       2010-04-06           -7
12799  2010     2010-06-18       2010-06-17           -1
16815  2010     2010-02-17       2010-01-12          -36
18950  2010     2010-10-16       2010-03-17         -213
18951  2010     2010-10-16       2010-03-17         -213
24855  2010     2010-09-14       2010-09-13           -1
26486  2010     2010-03-30       2010-03-29           -1
26487  2010     2010-03-30       2010-03-29           -1
26488  2010     2010-03-30       2010-03-29           -1
26489  2010     2010-03-30       2010-03-29           -1
26490  2010     2010-03-30       2010-03-29           -1
26491  2010     2010-03-30       2010-03-29           -1
26492  2010     2010-03-30       2010-03-29           -1
26493  2010     2010-03-30       2010-03-29           -1
26494  2010     2010-03-30       2010-03-29           -1

In [39]:
print(negative["delays_days"].describe())

count     68204.000000
mean      -3862.108425
std       49062.020589
min     -734138.000000
25%        -158.000000
50%         -23.000000
75%          -4.000000
max          -1.000000
Name: delays_days, dtype: float64

In [40]:
print(
    negative["year"].value_counts().sort_index()
)

year
2010    25758
2011    19946
2012    22500
Name: count, dtype: int64

In [41]:
print(
    data[data["delays_days"] < 0][
        ["year", "date_of_filing", "date_of_decision"]
    ].head(50).to_string(index=False)
)

 year date_of_filing date_of_decision
 2010     2010-01-07       2010-01-04
 2010     2010-12-22       2010-12-02
 2010     2010-10-30       2010-03-06
 2010     2010-11-08       2010-11-01
 2010     2010-03-30       2010-03-29
 2010     2010-04-13       2010-04-06
 2010     2010-06-18       2010-06-17
 2010     2010-02-17       2010-01-12
 2010     2010-10-16       2010-03-17
 2010     2010-10-16       2010-03-17
 2010     2010-09-14       2010-09-13
 2010     2010-03-30       2010-03-29
 2010     2010-03-30       2010-03-29
 2010     2010-03-30       2010-03-29
 2010     2010-03-30       2010-03-29
 2010     2010-03-30       2010-03-29
 2010     2010-03-30       2010-03-29
 2010     2010-03-30       2010-03-29
 2010     2010-03-30       2010-03-29
 2010     2010-03-30       2010-03-29
 2010     2010-04-20       2010-04-15
 2010     2010-04-20       2010-04-15
 2010     2010-04-20       2010-04-15
 2010     2010-04-20       2010-04-15
 2010     2010-04-20       2010-04-12
 2010     2010-06-29       2010-06-25
 2010     2010-07-28       2010-07-27
 2010     2010-07-28       2010-07-27
 2010     2010-01-16       2010-01-08
 2010     2010-07-09       2010-02-26
 2010     2010-10-13       2010-03-20
 2010     2010-05-07       2010-04-22
 2010     2010-01-05       2009-05-13
 2010     2010-03-03       2010-01-04
 2010     2010-03-03       2010-02-06
 2010     2010-03-03       2010-02-24
 2010     2010-03-03       2010-02-25
 2010     2010-03-03       2010-02-25
 2010     2010-03-03       2010-02-25
 2010     2010-03-03       2010-02-25
 2010     2010-03-03       2010-02-25
 2010     2010-03-03       2010-02-26
 2010     2010-10-28       2010-03-20
 2010     2010-10-28       2010-03-20
 2010     2010-10-28       2010-03-25
 2010     2010-10-28       2010-03-25
 2010     2010-10-28       2010-04-19
 2010     2010-10-28       2010-04-19
 2010     2010-10-28       2010-04-19
 2010     2010-10-28       2010-04-19

In [42]:
data = data[data["delays_days"] >= 0].copy()

In [43]:
print("Missing:", data["delays_days"].isna().sum())
print("Negative:", (data["delays_days"] < 0).sum())
print("Rows:", len(data))

Missing: 0
Negative: 0
Rows: 13689482

In [44]:
print(
    data["delays_days"].describe(
        percentiles=[
            0.50,
            0.75,
            0.90,
            0.95,
            0.99,
            0.995
        ]
    )
)

count    1.368948e+07
mean     9.282153e+02
std      5.258054e+03
min      0.000000e+00
50%      7.130000e+02
75%      1.430000e+03
90%      2.114000e+03
95%      2.441000e+03
99%      2.942000e+03
99.5%    3.083000e+03
max      1.895963e+06
Name: delays_days, dtype: float64

In [45]:
print("Minimum:", data["delays_days"].min())
print("Maximum:", data["delays_days"].max())

Minimum: 0
Maximum: 1895963

In [46]:
data['log_delay']=np.log1p(data['delays_days'])

In [47]:
data.info()

<class 'pandas.DataFrame'>
Index: 13689482 entries, 0 to 15890762
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   ddl_case_id        str
 1   year               int64
 2   state_code         int64
 3   dist_code          int64
 4   court_no           int64
 5   cino               str
 6   judge_position     str
 7   female_defendant   str
 8   female_petitioner  str
 9   female_adv_def     int64
 10  female_adv_pet     int64
 11  type_name          int64
 12  purpose_name       float64
 13  disp_name          int64
 14  date_of_filing     datetime64[us]
 15  date_of_decision   datetime64[us]
 16  delays_days        int64
 17  log_delay          float64
dtypes: datetime64[us](2), float64(2), int64(9), str(5)
memory usage: 1.9 GB

In [48]:
data['date_of_decision'].isnull().sum()

np.int64(0)

In [49]:
# now transfrom our datasets for preprosessing of data
# removing the ddl_case_id and cino column
data=data.drop(columns=['ddl_case_id','cino'])

In [50]:
data.head()

,year,state_code,dist_code,court_no,judge_position,female_defendant,female_petitioner,female_adv_def,female_adv_pet,type_name,purpose_name,disp_name,date_of_filing,date_of_decision,delays_days,log_delay
0,2010,1,1,1,chief judicial magistrate,0 male,1 female,0,-9998,790,5228.0,42,2010-12-13,2011-06-19,188,5.241747
1,2010,1,1,1,chief judicial magistrate,-9998 unclear,1 female,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,269,5.598422
2,2010,1,1,1,chief judicial magistrate,-9998 unclear,-9998 unclear,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,269,5.598422
3,2010,1,1,1,chief judicial magistrate,-9998 unclear,1 female,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,269,5.598422
4,2010,1,1,1,chief judicial magistrate,-9998 unclear,-9998 unclear,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,269,5.598422

In [51]:
for col in [
    "state_code",
    "dist_code",
    "court_no",
    "judge_position",
    "type_name",
    "purpose_name",
    "disp_name"
]:
    print(col, ":", data[col].nunique())

state_code : 32
dist_code : 75
court_no : 67
judge_position : 468
type_name : 6786
purpose_name : 7187
disp_name : 51

In [52]:
for col in [
    "female_defendant",
    "female_petitioner",
    "female_adv_def",
    "female_adv_pet"
]:
    print("\n", col)
    print(data[col].value_counts())

 female_defendant
female_defendant
0 male                9105200
-9998 unclear         2715160
1 female              1773545
-9999 missing name      95577
Name: count, dtype: int64

 female_petitioner
female_petitioner
-9998 unclear         5955516
0 male                5436504
1 female              2252471
-9999 missing name      44991
Name: count, dtype: int64

 female_adv_def
female_adv_def
-9999    10449901
 0        2622981
-9998      376261
 1         240339
Name: count, dtype: int64

 female_adv_pet
female_adv_pet
-9999    5861856
 0       5579663
-9998    1652700
 1        595263
Name: count, dtype: int64

In [53]:
# converting the date_of_filing
data["filing_year"] = data["date_of_filing"].dt.year
data["filing_month"] = data["date_of_filing"].dt.month
data["filing_dayofweek"] = data["date_of_filing"].dt.dayofweek

In [54]:
data.head()

,year,state_code,dist_code,court_no,judge_position,female_defendant,female_petitioner,female_adv_def,female_adv_pet,type_name,purpose_name,disp_name,date_of_filing,date_of_decision,delays_days,log_delay,filing_year,filing_month,filing_dayofweek
0,2010,1,1,1,chief judicial magistrate,0 male,1 female,0,-9998,790,5228.0,42,2010-12-13,2011-06-19,188,5.241747,2010,12,0
1,2010,1,1,1,chief judicial magistrate,-9998 unclear,1 female,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,269,5.598422,2010,2,3
2,2010,1,1,1,chief judicial magistrate,-9998 unclear,-9998 unclear,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,269,5.598422,2010,2,3
3,2010,1,1,1,chief judicial magistrate,-9998 unclear,1 female,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,269,5.598422,2010,2,3
4,2010,1,1,1,chief judicial magistrate,-9998 unclear,-9998 unclear,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,269,5.598422,2010,2,3

In [55]:
data1=data.drop(columns=['year','date_of_filing','date_of_decision','disp_name'])

In [56]:
data1.columns

Index(['state_code', 'dist_code', 'court_no', 'judge_position',
       'female_defendant', 'female_petitioner', 'female_adv_def',
       'female_adv_pet', 'type_name', 'purpose_name', 'delays_days',
       'log_delay', 'filing_year', 'filing_month', 'filing_dayofweek'],
      dtype='str')

In [57]:
# now we do train test split as on the basis of year
# 2010-2013=training set
# 2014 is validation set
# 2015 is test set
train=data1[data1['filing_year']==2010]
val=data1[data1['filing_year']==2011]
test=data1[data1['filing_year']==2012]

In [58]:
print(train.shape)
print(val.shape)
print(test.shape)

(3684901, 15)
(4511955, 15)
(5492626, 15)

In [59]:
print(train["filing_year"].value_counts().sort_index())
print(val["filing_year"].value_counts().sort_index())
print(test["filing_year"].value_counts().sort_index())

filing_year
2010    3684901
Name: count, dtype: int64
filing_year
2011    4511955
Name: count, dtype: int64
filing_year
2012    5492626
Name: count, dtype: int64

In [60]:
train.head()

,state_code,dist_code,court_no,judge_position,female_defendant,female_petitioner,female_adv_def,female_adv_pet,type_name,purpose_name,delays_days,log_delay,filing_year,filing_month,filing_dayofweek
0,1,1,1,chief judicial magistrate,0 male,1 female,0,-9998,790,5228.0,188,5.241747,2010,12,0
1,1,1,1,chief judicial magistrate,-9998 unclear,1 female,-9999,0,2587,3627.0,269,5.598422,2010,2,3
2,1,1,1,chief judicial magistrate,-9998 unclear,-9998 unclear,-9999,0,2587,3627.0,269,5.598422,2010,2,3
3,1,1,1,chief judicial magistrate,-9998 unclear,1 female,-9999,0,2587,3627.0,269,5.598422,2010,2,3
4,1,1,1,chief judicial magistrate,-9998 unclear,-9998 unclear,-9999,0,2587,3627.0,269,5.598422,2010,2,3

In [61]:
# saprating x_train and y_train and also for test and validation
X_train=train.drop(columns=['delays_days','log_delay'])
y_train=train['log_delay']

X_val=val.drop(columns=['delays_days','log_delay'])
y_val=val['log_delay']

X_test=test.drop(columns=['delays_days','log_delay'])
y_test=test['log_delay']

In [62]:
print(X_train.shape)
print(y_train.shape)
print(X_val.shape)
print(y_val.shape)
print(X_test.shape)
print(y_test.shape)

(3684901, 13)
(3684901,)
(4511955, 13)
(4511955,)
(5492626, 13)
(5492626,)

In [63]:
categorical_cols = [
    "state_code",
    "dist_code",
    "court_no",
    "judge_position",
    "female_defendant",
    "female_petitioner",
    "female_adv_def",
    "female_adv_pet",
    "type_name",
    "purpose_name"
]
numeric_cols = [
    "filing_year",
    "filing_month",
    "filing_dayofweek"
]

In [64]:
print(X_train[categorical_cols].dtypes)
print(X_train[numeric_cols].dtypes)
print(X_train[categorical_cols].isna().sum())

state_code             int64
dist_code              int64
court_no               int64
judge_position           str
female_defendant         str
female_petitioner        str
female_adv_def         int64
female_adv_pet         int64
type_name              int64
purpose_name         float64
dtype: object
filing_year         int32
filing_month        int32
filing_dayofweek    int32
dtype: object
state_code           0
dist_code            0
court_no             0
judge_position       0
female_defendant     0
female_petitioner    0
female_adv_def       0
female_adv_pet       0
type_name            0
purpose_name         0
dtype: int64

In [65]:
for col in categorical_cols:
    train_values = set(X_train[col].unique())
    val_values = set(X_val[col].unique())
    test_values = set(X_test[col].unique())

    unseen_val = val_values - train_values
    unseen_test = test_values - train_values

    print(f"\n{col}")
    print("Train categories:", len(train_values))
    print("Unseen in validation:", len(unseen_val))
    print("Unseen in test:", len(unseen_test))

state_code
Train categories: 31
Unseen in validation: 1
Unseen in test: 1

dist_code
Train categories: 75
Unseen in validation: 0
Unseen in test: 0

court_no
Train categories: 65
Unseen in validation: 1
Unseen in test: 2

judge_position
Train categories: 418
Unseen in validation: 32
Unseen in test: 42

female_defendant
Train categories: 4
Unseen in validation: 0
Unseen in test: 0

female_petitioner
Train categories: 4
Unseen in validation: 0
Unseen in test: 0

female_adv_def
Train categories: 4
Unseen in validation: 0
Unseen in test: 0

female_adv_pet
Train categories: 4
Unseen in validation: 0
Unseen in test: 0

type_name
Train categories: 5157
Unseen in validation: 1021
Unseen in test: 1563

purpose_name
Train categories: 4654
Unseen in validation: 1722
Unseen in test: 2260

In [66]:
# encodding for the categorical columns
category_maps = {}

for col in categorical_cols:
    unique_values = X_train[col].unique()

    # Start category IDs from 1
    mapping = {
        value: idx + 1
        for idx, value in enumerate(unique_values)
    }

    category_maps[col] = mapping

In [67]:
def encode_categories(df, category_maps):
    df = df.copy()

    for col, mapping in category_maps.items():
        df[col] = df[col].map(mapping).fillna(0).astype("int32")

    return df

In [68]:
X_train_encoded = encode_categories(X_train, category_maps)
X_val_encoded = encode_categories(X_val, category_maps)
X_test_encoded = encode_categories(X_test, category_maps)

In [69]:
print(X_train_encoded[categorical_cols].dtypes)
print(X_train_encoded[categorical_cols].head())

state_code           int32
dist_code            int32
court_no             int32
judge_position       int32
female_defendant     int32
female_petitioner    int32
female_adv_def       int32
female_adv_pet       int32
type_name            int32
purpose_name         int32
dtype: object
   state_code  dist_code  court_no  judge_position  female_defendant  \
0           1          1         1               1                 1
1           1          1         1               1                 2
2           1          1         1               1                 2
3           1          1         1               1                 2
4           1          1         1               1                 2

   female_petitioner  female_adv_def  female_adv_pet  type_name  purpose_name
0                  1               1               1          1             1
1                  1               2               2          2             2
2                  2               2               2          2             2
3                  1               2               2          2             2
4                  2               2               2          2             2

In [70]:
for col in categorical_cols:
    print(
        col,
        "UNK in validation:",
        (X_val_encoded[col] == 0).sum(),
        "UNK in test:",
        (X_test_encoded[col] == 0).sum()
    )

state_code UNK in validation: 3 UNK in test: 12
dist_code UNK in validation: 0 UNK in test: 0
court_no UNK in validation: 1 UNK in test: 7
judge_position UNK in validation: 249 UNK in test: 2946
female_defendant UNK in validation: 0 UNK in test: 0
female_petitioner UNK in validation: 0 UNK in test: 0
female_adv_def UNK in validation: 0 UNK in test: 0
female_adv_pet UNK in validation: 0 UNK in test: 0
type_name UNK in validation: 480375 UNK in test: 1135300
purpose_name UNK in validation: 1028806 UNK in test: 1487254

In [71]:
#creating the numerical features as we need for neural network
def create_numeric_features(df):
    result = pd.DataFrame(index=df.index)

    result["filing_year"] = df["filing_year"]

    result["month_sin"] = np.sin(
        2 * np.pi * df["filing_month"] / 12
    )

    result["month_cos"] = np.cos(
        2 * np.pi * df["filing_month"] / 12
    )

    result["day_sin"] = np.sin(
        2 * np.pi * df["filing_dayofweek"] / 7
    )

    result["day_cos"] = np.cos(
        2 * np.pi * df["filing_dayofweek"] / 7
    )

    return result

In [72]:
# tranforming the numerical values
X_train_numeric = create_numeric_features(X_train)
X_val_numeric = create_numeric_features(X_val)
X_test_numeric = create_numeric_features(X_test)

In [73]:
# scaling the numerical values
from sklearn.preprocessing import StandardScaler

numeric_scaler = StandardScaler()

X_train_numeric = numeric_scaler.fit_transform(
    X_train_numeric
)

X_val_numeric = numeric_scaler.transform(
    X_val_numeric
)

X_test_numeric = numeric_scaler.transform(
    X_test_numeric
)

In [74]:
embedding_dims = {
    "state_code": 4,
    "dist_code": 8,
    "court_no": 8,
    "judge_position": 16,
    "female_defendant": 4,
    "female_petitioner": 4,
    "female_adv_def": 4,
    "female_adv_pet": 4,
    "type_name": 32,
    "purpose_name": 32
}

In [75]:
embedding_input_dims = {
    col: len(category_maps[col]) + 1
    for col in categorical_cols
}

In [76]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [77]:
categorical_inputs = {}
embeddings = []

for col in categorical_cols:

    input_layer = keras.Input(
        shape=(1,),
        name=col,
        dtype="int32"
    )

    embedding = layers.Embedding(
        input_dim=embedding_input_dims[col],
        output_dim=embedding_dims[col],
        name=f"{col}_embedding"
    )(input_layer)

    embedding = layers.Flatten()(embedding)

    categorical_inputs[col] = input_layer
    embeddings.append(embedding)

In [78]:
numeric_input = keras.Input(
    shape=(5,),
    name="numeric_features",
    dtype="float32"
)

In [79]:
combined = layers.Concatenate()(
    embeddings + [numeric_input]
)

In [80]:
x = layers.Dense(128, activation="relu")(combined)

x = layers.Dropout(0.2)(x)

x = layers.Dense(64, activation="relu")(x)

x = layers.Dropout(0.2)(x)

x = layers.Dense(32, activation="relu")(x)

output = layers.Dense(1, name="output")(x)

In [81]:
model = keras.Model(
    inputs=list(categorical_inputs.values()) + [numeric_input],
    outputs=output
)

In [82]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ state_code          │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dist_code           │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ court_no            │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ judge_position      │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ female_defendant    │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ female_petitioner   │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ female_adv_def      │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ female_adv_pet      │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ type_name           │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ purpose_name        │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ state_code_embeddi… │ (None, 1, 4)      │        128 │ state_code[0][0]  │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dist_code_embedding │ (None, 1, 8)      │        608 │ dist_code[0][0]   │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ court_no_embedding  │ (None, 1, 8)      │        528 │ court_no[0][0]    │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ judge_position_emb… │ (None, 1, 16)     │      6,704 │ judge_position[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ female_defendant_e… │ (None, 1, 4)      │         20 │ female_defendant… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ female_petitioner_… │ (None, 1, 4)      │         20 │ female_petitione… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ female_adv_def_emb… │ (None, 1, 4)      │         20 │ female_adv_def[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ female_adv_pet_emb… │ (None, 1, 4)      │         20 │ female_adv_pet[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ type_name_embedding │ (None, 1, 32)     │    165,056 │ type_name[0][0]   │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ purpose_name_embed… │ (None, 1, 32)     │    148,960 │ purpose_name[0][… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 4)         │          0 │ state_code_embed… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_1 (Flatten) │ (None, 8)         │          0 │ dist_code_embedd… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_2 (Flatten) │ (None, 8)         │          0 │ court_no_embeddi… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_3 (Flatten) │ (None, 16)        │          0 │ judge_position_e… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_4 (Flatten) │ (None, 4)         │          0 │ female_defendant… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_5 (Flatten) │ (None, 4)         │          0 │ female_petitione… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_6 (Flatten) │ (None, 4)         │          0 │ female_adv_def_e… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_7 (Flatten) │ (None, 4)         │          0 │ female_adv_pet_e… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_8 (Flatten) │ (None, 32)        │          0 │ type_name_embedd… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_9 (Flatten) │ (None, 32)        │          0 │ purpose_name_emb… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ numeric_features    │ (None, 5)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 121)       │          0 │ flatten[0][0],    │
│ (Concatenate)       │                   │            │ flatten_1[0][0],  │
│                     │                   │            │ flatten_2[0][0],  │
│                     │                   │            │ flatten_3[0][0],  │
│                     │                   │            │ flatten_4[0][0],  │
│                     │                   │            │ flatten_5[0][0],  │
│                     │                   │            │ flatten_6[0][0],  │
│                     │                   │            │ flatten_7[0][0],  │
│                     │                   │            │ flatten_8[0][0],  │
│                     │                   │            │ flatten_9[0][0],  │
│                     │                   │            │ numeric_features… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 128)       │     15,616 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 128)       │          0 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 64)        │      8,256 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 64)        │          0 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 32)        │      2,080 │ dropout_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ output (Dense)      │ (None, 1)         │         33 │ dense_2[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 348,049 (1.33 MB)

 Trainable params: 348,049 (1.33 MB)

 Non-trainable params: 0 (0.00 B)

In [83]:
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss=keras.losses.Huber(),
    metrics=[
        keras.metrics.MeanAbsoluteError(name="mae")
    ]
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [84]:
train_inputs = {
    col: X_train_encoded[col].values
    for col in categorical_cols
}

train_inputs["numeric_features"] = X_train_numeric

In [85]:
val_inputs = {
    col: X_val_encoded[col].values
    for col in categorical_cols
}

val_inputs["numeric_features"] = X_val_numeric

In [86]:
test_inputs = {
    col: X_test_encoded[col].values
    for col in categorical_cols
}

test_inputs["numeric_features"] = X_test_numeric

In [87]:
history = model.fit(
    train_inputs,
    y_train,
    validation_data=(val_inputs, y_val),
    epochs=3,
    batch_size=4096,
    callbacks=[
        keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=2,
            restore_best_weights=True
        )
    ]
)

Epoch 1/3
900/900 ━━━━━━━━━━━━━━━━━━━━ 22s 20ms/step - loss: 0.7179 - mae: 1.0942 - val_loss: 0.9369 - val_mae: 1.3646
Epoch 2/3
900/900 ━━━━━━━━━━━━━━━━━━━━ 17s 19ms/step - loss: 0.4730 - mae: 0.8135 - val_loss: 0.8496 - val_mae: 1.2534
Epoch 3/3
900/900 ━━━━━━━━━━━━━━━━━━━━ 18s 20ms/step - loss: 0.4246 - mae: 0.7515 - val_loss: 0.8303 - val_mae: 1.2220

In [88]:
pred_log = model.predict(test_inputs)

pred_days = np.expm1(pred_log.ravel())

171645/171645 ━━━━━━━━━━━━━━━━━━━━ 342s 2ms/step

In [89]:
actual_days = test["delays_days"].values

In [90]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(actual_days, pred_days)

rmse = np.sqrt(
    mean_squared_error(actual_days, pred_days)
)

r2 = r2_score(actual_days, pred_days)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 656.949462890625
RMSE: 5912.832823613399
R2: -0.003009200096130371

In [91]:
print("Predicted:")
print(pd.Series(pred_days).describe())

print("\nActual:")
print(pd.Series(actual_days).describe())

Predicted:
count    5.492626e+06
mean     9.421235e+02
std      4.741201e+02
min      3.005853e-01
25%      6.153494e+02
50%      8.950588e+02
75%      1.213521e+03
max      6.117045e+03
dtype: float64

Actual:
count    5.492626e+06
mean     7.930962e+02
std      5.903957e+03
min      0.000000e+00
25%      1.540000e+02
50%      5.720000e+02
75%      1.211000e+03
max      1.529922e+06
dtype: float64

In [92]:
baseline_prediction = np.median(np.expm1(y_train))

baseline_pred = np.full(
    len(actual_days),
    baseline_prediction
)

print("Baseline prediction:", baseline_prediction)
print("Baseline MAE:",
      mean_absolute_error(actual_days, baseline_pred))
print("Baseline RMSE:",
      np.sqrt(mean_squared_error(actual_days, baseline_pred)))
print("Baseline R2:",
      r2_score(actual_days, baseline_pred))

Baseline prediction: 922.9999999999999
Baseline MAE: 652.3989980384611
Baseline RMSE: 5905.385520652035
Baseline R2: -0.0004841252413336772

In [93]:
print("data:", data.shape)

print("\nYears:")
print(data["year"].value_counts().sort_index())

data: (13689482, 19)

Years:
year
2010    3684901
2011    4511955
2012    5492626
Name: count, dtype: int64

In [94]:
baseline_prediction = np.median(np.expm1(y_train))
baseline_prediction

np.float64(922.9999999999999)

In [95]:
print("y_train rows:", len(y_train))
print("y_test rows:", len(y_test))

print("Actual test rows:", len(actual_days))

print("Median training delay:",
      np.median(np.expm1(y_train)))

print("Median actual test delay:",
      np.median(actual_days))

y_train rows: 3684901
y_test rows: 5492626
Actual test rows: 5492626
Median training delay: 922.9999999999999
Median actual test delay: 572.0

In [96]:
print("Test years:")
print(test["filing_year"].value_counts().sort_index())

Test years:
filing_year
2012    5492626
Name: count, dtype: int64